/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author davidf
 */
public class ViewGuerras extends JDialog {

    /**
     * Creates new form warView
     *
     * @param parent
     * @param modal
     */
    
      ImagenPanel fondo = new ImagenPanel();
    public ViewGuerras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        this.setContentPane(fondo);
        initComponents();
        setWindow();
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public void setJtableWars(JTable jtableWars) {
        this.jtableWars = jtableWars;
    }

    public JButton getBtnLimpiarPantalla() {
        return btnLimpiarPantalla;
    }

    public JButton getAdd_button() {
        return add_button;
    }

    public JButton getDelete_button() {
        return delete_button;
    }

    public JButton getEdit_button() {
        return edit_button;
    }

    public JTextField getEnd_date_text() {
        return end_date_text;
    }

    public JButton getExit_button() {
        return exit_button;
    }

    public JTextField getId_text() {
        return id_text;
    }

    public JTable getJtableWars() {
        return jtableWars;
    }

    public JTextField getName_text() {
        return name_text;
    }

    public JTextField getStart_date_text() {
        return start_date_text;
    }

    public JTextField getTxtfFilterSearch() {
        return txtfFilterSearch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        edit_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        btnLimpiarPantalla = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name_text = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        start_date_text = new javax.swing.JTextField();
        start_date_label = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        end_date_label = new javax.swing.JLabel();
        end_date_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableWars = new javax.swing.JTable();
        txtfFilterSearch = new javax.swing.JTextField();
        lblFilterSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1237, 676));
        setMinimumSize(new java.awt.Dimension(1237, 676));
        setResizable(false);
        setSize(new java.awt.Dimension(1237, 676));

        jPanel2.setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(172, 533));

        edit_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edit_button.setText("Modificar");
        edit_button.setPreferredSize(new java.awt.Dimension(120, 62));

        delete_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        delete_button.setText("Eliminar");
        delete_button.setPreferredSize(new java.awt.Dimension(120, 62));

        add_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_button.setText("Añadir");
        add_button.setPreferredSize(new java.awt.Dimension(120, 62));

        exit_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salir.png"))); // NOI18N
        exit_button.setBorderPainted(false);
        exit_button.setContentAreaFilled(false);
        exit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_button.setDefaultCapable(false);
        exit_button.setFocusPainted(false);
        exit_button.setFocusable(false);
        exit_button.setPreferredSize(new java.awt.Dimension(120, 62));
        exit_button.setRequestFocusEnabled(false);

        btnLimpiarPantalla.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpiarPantalla.setText("Limpiar Pant");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guerras.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(exit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(name_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 410, 30));

        name_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name_label.setForeground(new java.awt.Color(204, 204, 204));
        name_label.setText("Nombre de la Guerra:");
        jPanel1.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));
        jPanel1.add(start_date_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 190, 30));

        start_date_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        start_date_label.setForeground(new java.awt.Color(204, 204, 204));
        start_date_label.setText("Fecha de inicio:");
        jPanel1.add(start_date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 160, 30));
        jPanel1.add(id_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 30));

        id_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id_label.setForeground(new java.awt.Color(204, 204, 204));
        id_label.setText("ID Guerra:");
        jPanel1.add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 30));

        end_date_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        end_date_label.setForeground(new java.awt.Color(204, 204, 204));
        end_date_label.setText("Fecha de fin:");
        jPanel1.add(end_date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 120, 30));
        jPanel1.add(end_date_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 81, 190, 30));

        jtableWars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtableWars.setOpaque(false);
        jScrollPane1.setViewportView(jtableWars);

        lblFilterSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFilterSearch.setForeground(new java.awt.Color(204, 204, 204));
        lblFilterSearch.setText("Busqueda:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(lblFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFilterSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton btnLimpiarPantalla;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton edit_button;
    private javax.swing.JLabel end_date_label;
    private javax.swing.JTextField end_date_text;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_text;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableWars;
    private javax.swing.JLabel lblFilterSearch;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel start_date_label;
    private javax.swing.JTextField start_date_text;
    private javax.swing.JTextField txtfFilterSearch;
    // End of variables declaration//GEN-END:variables

    private void setWindow() {
        setTitle("GUERRAS");
        setLocationRelativeTo(this);
    }

}
