/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author davidf
 */
public class ViewGuerras extends JDialog {

    /**
     * Creates new form warView
     *
     * @param parent
     * @param modal
     */
    
      ImagenPanel fondo = new ImagenPanel();
    public ViewGuerras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

             this.setContentPane(fondo);
        initComponents();
        setWindow();

    }

    public JButton getBtnLimpiarPantalla() {
        return btnLimpiarPantalla;
    }

    public JButton getAdd_button() {
        return add_button;
    }

    public JButton getDelete_button() {
        return delete_button;
    }

    public JButton getEdit_button() {
        return edit_button;
    }

    public JTextField getEnd_date_text() {
        return end_date_text;
    }

    public JButton getExit_button() {
        return exit_button;
    }

    public JTextField getId_text() {
        return id_text;
    }

    public JTable getJtableWars() {
        return jtableWars;
    }

    public JTextField getName_text() {
        return name_text;
    }

    public JTextField getStart_date_text() {
        return start_date_text;
    }

    public JTextField getTxtfFilterSearch() {
        return txtfFilterSearch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFilterSearch = new javax.swing.JLabel();
        txtfFilterSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableWars = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        name_text = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        start_date_text = new javax.swing.JTextField();
        start_date_label = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        end_date_label = new javax.swing.JLabel();
        end_date_text = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        edit_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        btnLimpiarPantalla = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFilterSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFilterSearch.setForeground(new java.awt.Color(204, 204, 204));
        lblFilterSearch.setText("Busqueda");

        jtableWars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtableWars.setOpaque(false);
        jScrollPane1.setViewportView(jtableWars);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(name_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 410, 28));

        name_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_label.setForeground(new java.awt.Color(204, 204, 204));
        name_label.setText("Nombre de la Guerra:");
        jPanel1.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel1.add(start_date_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 180, 28));

        start_date_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        start_date_label.setForeground(new java.awt.Color(204, 204, 204));
        start_date_label.setText("Fecha de inicio:");
        jPanel1.add(start_date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 129, -1));
        jPanel1.add(id_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 28));

        id_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_label.setForeground(new java.awt.Color(204, 204, 204));
        id_label.setText("ID Guerra:");
        jPanel1.add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, -1));

        end_date_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        end_date_label.setForeground(new java.awt.Color(204, 204, 204));
        end_date_label.setText("Fecha de fin:");
        jPanel1.add(end_date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 110, -1));
        jPanel1.add(end_date_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 180, 31));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(172, 533));

        edit_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edit_button.setText("Modificar");
        edit_button.setPreferredSize(new java.awt.Dimension(120, 62));

        delete_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        delete_button.setText("Eliminar");
        delete_button.setPreferredSize(new java.awt.Dimension(120, 62));

        add_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_button.setText("Añadir");
        add_button.setPreferredSize(new java.awt.Dimension(120, 62));

        exit_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit_button.setText("Salir");
        exit_button.setPreferredSize(new java.awt.Dimension(120, 62));

        btnLimpiarPantalla.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpiarPantalla.setText("Limpiar Pant");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guerras.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(exit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfFilterSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFilterSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton btnLimpiarPantalla;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton edit_button;
    private javax.swing.JLabel end_date_label;
    private javax.swing.JTextField end_date_text;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_text;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableWars;
    private javax.swing.JLabel lblFilterSearch;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel start_date_label;
    private javax.swing.JTextField start_date_text;
    private javax.swing.JTextField txtfFilterSearch;
    // End of variables declaration//GEN-END:variables

    private void setWindow() {
        setTitle("GUERRAS");
        setLocationRelativeTo(this);
    }

}
