/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author davidf
 */
public class ViewPaises extends JDialog {

    /**
     * Creates new form viewCountrie
     * @param parent
     * @param modal
     */
    
    ImagenPanel fondo = new ImagenPanel();
     
     public ViewPaises(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
    this.setContentPane(fondo);
        
        initComponents();
       setWindow();
    }

    public JButton getBtnLimpiarPantalla() {
        return btnLimpiarPantalla;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public JButton getBtnInsert() {
        return btnInsert;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public JCheckBox getCheckBoxIndependent() {
        return checkBoxIndependent;
    }

    public JTable getJtableCountries() {
        return jtableCountries;
    }

    public JLabel getLblCountryName() {
        return lblCountryId;
    }

    public JLabel getLblDateBegin() {
        return lblDateBegin;
    }

    public JLabel getLblDateEnd() {
        return lblDateEnd;
    }

    public JLabel getLblSearch() {
        return lblSearch;
    }

    public JTextField getTxtfCountryName() {
        return txtfCountryName;
    }

    public JTextField getTxtfDateBegin() {
        return txtfDateBegin;
    }

    public JTextField getTxtfDateEnd() {
        return txtfDateEnd;
    }

    public JTextField getTxtfSearch() {
        return txtfSearch;
    }

    public JTextField getTF_CountryId() {
	return TF_CountryId;
    }

    public void setTF_CountryId(JTextField TF_CountryId) {
	this.TF_CountryId = TF_CountryId;
    }
    

     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearch = new javax.swing.JLabel();
        txtfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableCountries = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblCountryId = new javax.swing.JLabel();
        txtfCountryName = new javax.swing.JTextField();
        checkBoxIndependent = new javax.swing.JCheckBox();
        lblDateBegin = new javax.swing.JLabel();
        txtfDateBegin = new javax.swing.JTextField();
        lblDateEnd = new javax.swing.JLabel();
        txtfDateEnd = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblCountryName1 = new javax.swing.JLabel();
        TF_CountryId = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnLimpiarPantalla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(204, 204, 204));
        lblSearch.setText("Busqueda:");

        jtableCountries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtableCountries);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCountryId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCountryId.setForeground(new java.awt.Color(204, 204, 204));
        lblCountryId.setText("Id. País:");
        jPanel2.add(lblCountryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 32));
        jPanel2.add(txtfCountryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 370, 30));

        checkBoxIndependent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkBoxIndependent.setForeground(new java.awt.Color(204, 204, 204));
        checkBoxIndependent.setText("País Independiente");
        checkBoxIndependent.setBorderPainted(true);
        checkBoxIndependent.setContentAreaFilled(false);
        checkBoxIndependent.setFocusable(false);
        jPanel2.add(checkBoxIndependent, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        lblDateBegin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDateBegin.setForeground(new java.awt.Color(204, 204, 204));
        lblDateBegin.setText("Año Inicio:");
        jPanel2.add(lblDateBegin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 101, 32));
        jPanel2.add(txtfDateBegin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 173, 32));

        lblDateEnd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDateEnd.setForeground(new java.awt.Color(204, 204, 204));
        lblDateEnd.setText("Año Fin:");
        jPanel2.add(lblDateEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 100, 30));
        jPanel2.add(txtfDateEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 173, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 10, -1, 150));

        lblCountryName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCountryName1.setForeground(new java.awt.Color(204, 204, 204));
        lblCountryName1.setText("Nombre País:");
        jPanel2.add(lblCountryName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 32));
        jPanel2.add(TF_CountryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);

        btnInsert.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInsert.setText("Insertar");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdate.setText("Modificar");

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Eliminar");

        btnLimpiarPantalla.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpiarPantalla.setText("Limpiar Pant");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mundi.png"))); // NOI18N

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salir.png"))); // NOI18N
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setDefaultCapable(false);
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnLimpiarPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_CountryId;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLimpiarPantalla;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox checkBoxIndependent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jtableCountries;
    private javax.swing.JLabel lblCountryId;
    private javax.swing.JLabel lblCountryName1;
    private javax.swing.JLabel lblDateBegin;
    private javax.swing.JLabel lblDateEnd;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTextField txtfCountryName;
    private javax.swing.JTextField txtfDateBegin;
    private javax.swing.JTextField txtfDateEnd;
    private javax.swing.JTextField txtfSearch;
    // End of variables declaration//GEN-END:variables
 private void setWindow() {
        setTitle("PAISES");
        setLocationRelativeTo(this);
    }

}

