package Models.POJOs;


// Generated 16 may. 2021 19:18:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,catalog="guerras"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Pais  implements java.io.Serializable {

     @Id 
     @GeneratedValue(strategy=IDENTITY)
     @Column(name="id_pais", unique=true, nullable=false)
     private Integer idPais;
     
     @Column(name="nombre", unique=true, nullable=false, length=50)
     private String nombre;
     
     @OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
     private Set periodoIndependecias = new HashSet(0);
     
     @OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
     private Set unionBandoses = new HashSet(0);

    public Pais() {
    }

	
    public Pais(String nombre) {
        this.nombre = nombre;
    }
    public Pais(String nombre, Set periodoIndependecias, Set unionBandoses) {
       this.nombre = nombre;
       this.periodoIndependecias = periodoIndependecias;
       this.unionBandoses = unionBandoses;
    }
   

    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }

    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getPeriodoIndependecias() {
        return this.periodoIndependecias;
    }
    
    public void setPeriodoIndependecias(Set periodoIndependecias) {
        this.periodoIndependecias = periodoIndependecias;
    }

    public Set getUnionBandoses() {
        return this.unionBandoses;
    }
    
    public void setUnionBandoses(Set unionBandoses) {
        this.unionBandoses = unionBandoses;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.idPais);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Pais other = (Pais) obj;
        if (!Objects.equals(this.idPais, other.idPais)) {
            return false;
        }
        return true;
    }




}


