package Models.POJOs;


// Generated 16 may. 2021 19:18:02 by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PeriodoIndependecia generated by hbm2java
 */
@Entity
@Table(name="periodo_independecia"
    ,catalog="guerras"
    , uniqueConstraints = @UniqueConstraint(columnNames="id_pais") 
)
public class PeriodoIndependecia  implements java.io.Serializable {


     private Integer idPeriodo;
     private Pais pais;
     private Integer anioInicio;
     private Integer anioFin;

    public PeriodoIndependecia() {
    }

	
    public PeriodoIndependecia(Pais pais, Integer anioInicio) {
        this.pais = pais;
        this.anioInicio = anioInicio;
    }
    public PeriodoIndependecia(Pais pais, Integer anioInicio, Integer anioFin) {
       this.pais = pais;
       this.anioInicio = anioInicio;
       this.anioFin = anioFin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_periodo", unique=true, nullable=false)
    public Integer getIdPeriodo() {
        return this.idPeriodo;
    }
    
    public void setIdPeriodo(Integer idPeriodo) {
        this.idPeriodo = idPeriodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pais", unique=true, nullable=false)
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    
    @Column(name="anio_inicio")
    public Integer getAnioInicio() {
        return this.anioInicio;
    }
    
    public void setAnioInicio(Integer anioInicio) {
        this.anioInicio = anioInicio;
    }

    
    @Column(name="anio_fin")
    public Integer getAnioFin() {
        return this.anioFin;
    }
    
    public void setAnioFin(Integer anioFin) {
        this.anioFin = anioFin;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 17 * hash + Objects.hashCode(this.idPeriodo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PeriodoIndependecia other = (PeriodoIndependecia) obj;
        if (!Objects.equals(this.idPeriodo, other.idPeriodo)) {
            return false;
        }
        return true;
    }




}


