package Models.POJOs;


// Generated 16 may. 2021 19:18:02 by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UnionBandos generated by hbm2java
 */
@Entity
@Table(name="union_bandos"
    ,catalog="guerras"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_pais", "id_contendiente"}) 
)
public class UnionBandos  implements java.io.Serializable {


     private Integer idUnionBandos;
     private Contendiente contendiente;
     private Pais pais;
     private String fechaUnion;
     private String fechaAbandono;

    public UnionBandos() {
    }

	
    public UnionBandos(Contendiente contendiente, Pais pais) {
        this.contendiente = contendiente;
        this.pais = pais;
    }
    public UnionBandos(Contendiente contendiente, Pais pais, String fechaUnion, String fechaAbandono) {
       this.contendiente = contendiente;
       this.pais = pais;
       this.fechaUnion = fechaUnion;
       this.fechaAbandono = fechaAbandono;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_union_bandos", unique=true, nullable=false)
    public Integer getIdUnionBandos() {
        return this.idUnionBandos;
    }
    
    public void setIdUnionBandos(Integer idUnionBandos) {
        this.idUnionBandos = idUnionBandos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_contendiente", nullable=false)
    public Contendiente getContendiente() {
        return this.contendiente;
    }
    
    public void setContendiente(Contendiente contendiente) {
        this.contendiente = contendiente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pais", nullable=false)
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    
    @Column(name="fecha_union", length=10)
    public String getFechaUnion() {
        return this.fechaUnion;
    }
    
    public void setFechaUnion(String fechaUnion) {
        this.fechaUnion = fechaUnion;
    }

    
    @Column(name="fecha_abandono", length=10)
    public String getFechaAbandono() {
        return this.fechaAbandono;
    }
    
    public void setFechaAbandono(String fechaAbandono) {
        this.fechaAbandono = fechaAbandono;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.idUnionBandos);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UnionBandos other = (UnionBandos) obj;
        if (!Objects.equals(this.idUnionBandos, other.idUnionBandos)) {
            return false;
        }
        return true;
    }




}


